# Generated by Django 3.1.1 on 2020-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LashGoldApps', '0002_practicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicearea',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
